---


AWSTemplateFormatVersion: 2010-09-09


Description: 'git LFS: SSL certificate for custom API endpoint'


Metadata:

   AWS::CloudFormation::Interface:
      ParameterLabels:
         DomainName:
            default: Domain name
         HostedZoneId:
            default: Hosted zone

      ParameterGroups:
         -
            Label: DNS
            Parameters:
               - DomainName
         -
            Label: Route 53
            Parameters:
               - HostedZoneId


Parameters:

   DomainName:
      Description: Domain name of git LFS API endpoint.
      Type: String

   HostedZoneId:
      Description: ID of the Route 53 hosted zone in which to create DNS records.
      Type: AWS::Route53::HostedZone::Id


Resources:

   Certificate:
      Type: AWS::CertificateManager::Certificate
      Properties:
         DomainName:
            Ref: DomainName
         ValidationMethod: DNS
         DomainValidationOptions:
            -
               DomainName:
                  Ref: DomainName
               HostedZoneId:
                  Ref: HostedZoneId
         Tags:
            -
               Key: Name
               Value: git-lfs


Outputs:

   CertificateArn:
      Description: ARN of the certificate.
      Value:
         Ref: Certificate
