---


AWSTemplateFormatVersion: 2010-09-09


Description: 'git LFS: Custom API endpoint'


Parameters:

   ApiId:
      Description: ID of the API.
      Type: String

   CertificateArn:
      Description: ARN of the certificate validating the git LFS endpoint domain.
      Type: String

   DomainName:
      Description: Domain name of git LFS API endpoint.
      Type: String

   HostedZoneId:
      Description: ID of the Route 53 hosted zone in which to create DNS records.
      Type: AWS::Route53::HostedZone::Id

   StageName:
      Description: Name of the API stage.
      Type: String


Resources:

   Record:
      DependsOn:
         - Mapping
      Type: AWS::Route53::RecordSet
      Properties:
         AliasTarget:
            DNSName:
               Fn::GetAtt:
                  - ApiDomainName
                  - RegionalDomainName
            HostedZoneId:
               Fn::GetAtt:
                  - ApiDomainName
                  - RegionalHostedZoneId
         Comment: git LFS
         HostedZoneId:
            Ref: HostedZoneId
         Name:
            Ref: DomainName
         Type: A

   ApiDomainName:
      Type: AWS::ApiGatewayV2::DomainName
      Properties:
         DomainName:
            Ref: DomainName
         DomainNameConfigurations:
            -
               CertificateArn:
                  Ref: CertificateArn
               EndpointType: REGIONAL

   Mapping:
      Type: AWS::ApiGatewayV2::ApiMapping
      Properties:
         ApiId:
            Ref: ApiId
         DomainName:
            Ref: ApiDomainName
         Stage:
            Ref: StageName
