---


AWSTemplateFormatVersion: 2010-09-09


Description: 'git LFS: Lock table'


Resources:

   Table:
      Type: AWS::DynamoDB::Table
      Properties:
         AttributeDefinitions:
            -
               AttributeName: path
               AttributeType: S
            -
               AttributeName: creation_time
               AttributeType: S
            -
               AttributeName: github_username
               AttributeType: S
         BillingMode: PAY_PER_REQUEST
         KeySchema:
            -
               AttributeName: path
               KeyType: HASH

   LockManagementPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
         Description:
            Fn::Sub: Manage git LFS locks on DynamoDB table ${Table}
         PolicyDocument:
            Version: 2012-10-17
            Statement:
               -
                  Action:
                     - dynamodb:PutItem
                  Resource:
                     -
                        Fn::GetAtt:
                           - Table
                           - Arn
                  Effect: Allow


Outputs:

   LockManagementPolicyArn:
      Description: ARN of the lock management policy.
      Value:
         Ref: LockManagementPolicy

   TableArn:
      Description: ARN of the DynamoDB table.
      Value:
         Fn::GetAtt:
            - Table
            - Arn

   TableName:
      Description: Name of the DynamoDB table.
      Value:
         Ref: Table
