---


AWSTemplateFormatVersion: 2010-09-09


Description: 'git LFS: API stage'


Metadata:

   AWS::CloudFormation::Interface:
      ParameterLabels:
         AccessLogs:
            default: Access logs?
         StageName:
            default: Stage name

      ParameterGroups:
         -
            Label: API Gateway
            Parameters:
               - ApiId
               - StageName
         -
            Label: Debugging
            Parameters:
               - AccessLogs


Parameters:

   AccessLogs:
      Description: Whether to enable API Gateway access logs.
      Type: String
      AllowedValues:
         - 'no'
         - 'yes'
      Default: 'no'

   ApiId:
      Description: ID of the API.
      Type: String

   StageName:
      Description: Name of the API stage.
      Type: String


Conditions:

   EnableAccessLogs:
      Fn::Equals:
         -
            Ref: AccessLogs
         - 'yes'


Resources:

   LogsGroup:
      Condition: EnableAccessLogs
      Type: AWS::Logs::LogGroup
      Properties:
         RetentionInDays: 7

   Stage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
         ApiId:
            Ref: ApiId
         StageName:
            Ref: StageName
         AccessLogSettings:
            Fn::If:
               - EnableAccessLogs
               -
                  DestinationArn:
                     Fn::GetAtt:
                        - LogsGroup
                        - Arn
                  Format: >-
                     $context.identity.sourceIp
                     -
                     -
                     [$context.requestTime]
                     "$context.httpMethod $context.routeKey $context.protocol"
                     $context.status
                     $context.responseLength
                     $context.requestId
               -
                  Ref: AWS::NoValue
         # StageVariables:
         AutoDeploy: true


Outputs:

   Name:
      Description: Name of the API stage.
      Value:
         Ref: Stage
